### ISSUE TITLE
What is the best way to include their mailchimp signup form?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/baltimorefoodhub#11]
made a mailchimp.txt file in content that has their naked form code...

**Comment by webmasterkai** [comment]
http://facebook.github.io/react/html-jsx.html is your friend :-) I used that to create the update in e6885b56e7b3d0a1932d033563a9e0b8862ef662

Inline styles are js objects instead of text strings.

**Comment by bjornmeansbear** [comment]
Cool, well I started a mailchimp jsx file, which I got to not break the page, but couldn't get it to actually show up :P

**Comment by webmasterkai** [comment]
variables of simple JSX code can go inside brackets `{variable}`
A component in a different file is a React Class and needs to be used inside a jsx tag `<Component />`
