### ISSUE TITLE
Clicking "reveal" button should show/hide menu in "mobile" mode

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/baltimorefoodhub#15]
We need to figure out a standard way of implementing this so it can be added to hunting ground and bmore bar guild too...

Also, what's the right way to decide what is "mobile" and what isn't??? (perhaps this is a separate discussion for us to have?)

**Comment by webmasterkai** [comment]
368cd65c49dbdad478f31c498fc066f5666fe230 imports our changes from mica. Should this be migrated to the other sites?

**Comment by bjornmeansbear** [comment]
Yeah, we should add this to Huntingground and Bmorebarguild... Am I missing anything? anything else we built with this so far?
