### ISSUE TITLE
Find out who the contact form is supposed to email

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/baltimorefoodhub#2]

**Comment by webmasterkai** [comment]
https://sundaysenergy.wufoo.com/build/baltimore-food-hub/ needs to be edited with the fields needed.
Email setting https://sundaysenergy.wufoo.com/notifications/baltimore-food-hub/

**Comment by bjornmeansbear** [comment]
Awesome. working on this.

**Comment by bjornmeansbear** [comment]
Okay! I got all their requested stuff... now I just need to know who to send it on too... I'll get that from them when they look it over.
