### ISSUE TITLE
Get a test url setup so I can share with clients while we develop

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/baltimorefoodhub#5]
I have a lot of questions for them, being able to just send them a link will make it easier (i hope) to get some answers quickly.

**Comment by bjornmeansbear** [comment]
bfh.ookb.co? or an ezle/cape subdomain?

**Comment by webmasterkai** [comment]
Since I have access to ezle.io domain I used that one. http://bfh.ezle.io

```
gulp deploy
```
